//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int rowid { get; set; }
        public string order_no { get; set; }
        public string client_no { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string remark { get; set; }
    }
}
