//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class re_complete_detail
    {
        public int rowid { get; set; }
        public string re_complete_no { get; set; }
        public string proc_no { get; set; }
        public string mach_no { get; set; }
        public Nullable<decimal> value1 { get; set; }
        public Nullable<decimal> value2 { get; set; }
        public Nullable<decimal> value3 { get; set; }
        public string user_no { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public Nullable<int> qty { get; set; }
        public string remark { get; set; }
    }
}
